Repository unb-mds/Squad09-UnBHUB, pull requests merged in 2024-09, with the labels that each got.

#170 Adição de script de testes unitários
  .github/workflows/jest_tests.yaml
  .gitignore
  documentation/mkdocs/docs/Reunioes/Reuniao24.md
  documentation/mkdocs/docs/Reunioes/Reuniao25.md
  documentation/mkdocs/docs/Sprints/Sprint12.md
  documentation/mkdocs/docs/Sprints/Sprint13.md
  jest.config.ts
  package.json
  src/__tests__/components/Cardapio/Calltoaction2.spec.tsx
  src/__tests__/components/Inputs/input.spec.tsx
  src/__tests__/components/Landing/Calltoaction.test.tsx
  src/__tests__/components/Landing/Hero.spec.tsx
  src/__tests__/components/Landing/navbar.spec.tsx
  src/__tests__/components/SignIn/Checkbox.spec.tsx
  src/__tests__/components/SignIn/SignInCard.spec.tsx
  src/__tests__/components/SignUp/SignUpCard.spec.tsx
  src/__tests__/functions/Calendar/HighlightUtils.spec.tsx
  tsconfig.json
Labels: Unit Tests

#171 Correção dos últimos bugs.
  src/components/Activities/editActivity.tsx
  src/components/Exams/CreateExamDialog.tsx
  src/components/Library/editBook.tsx
  src/components/Subject/ExamDialogComponent.tsx
  src/components/Subject/createSubject.tsx
Labels: Bug, Back-End

#172 Ajuste final do front-end da página
  public/Students_darkbg.png
  public/images/imglogin.svg
  public/images/planing.jpg
  src/components/Exams/ExamsComponent.tsx
  src/components/Landing/Hero.tsx
  src/components/Landing/feature.tsx
  src/main.tsx
  src/pages/ExamScreen.tsx
  src/pages/Landing.tsx
Labels: Front-End

#173 [PULLREQUEST] - Adição do arquivo vercel.json para correção das rotas no deploy.
  vercel.json
Labels: Front-End, High Priority

#174 Ajuste na documentação do projeto
  README.md
  documentation/mkdocs/docs/Arquitetura.md
  documentation/mkdocs/docs/Requisitos.md
  documentation/mkdocs/docs/Reunioes/Reuniao26.md
  documentation/mkdocs/docs/Sprints/Sprint14.md
  documentation/mkdocs/docs/assets/architecture.png
  documentation/mkdocs/docs/assets/newArchitecture.png
  documentation/mkdocs/mkdocs.yml
  index.html
Labels: Documentação
