Repository unb-mds/Squad09-UnBHUB, pull requests merged in 2024-08, with the labels that each got.

#116 Atualização do formulário de adição de matérias e provas
  src/components/Activities/SearchDropdown.tsx
  src/components/Activities/StatusComponent.tsx
  src/components/Activities/createActivity.tsx
  src/components/Activities/editActivity.tsx
  src/components/ActivitiesComponent.tsx
  src/components/Calendar/CalendarComponent.tsx
  src/components/Calendar/DataLivros.tsx
  src/components/DisplayMenu.tsx
  src/components/Subject/EditExamDialog.tsx
  src/components/Subject/EditSubjectComponent.tsx
  src/components/Subject/ExamDialogComponent.tsx
  src/components/Subject/SpecificSubjectTasks.tsx
  src/components/Subject/SubjectDetailsComponent.tsx
  src/components/Subject/SubjectDialogComponent.tsx
  src/components/Subject/SubjectSpecificExams.tsx
  src/components/Subject/SubjectsComponents.tsx
  src/components/Subject/createSubject.tsx
  src/components/Subject/subjectsCardConstructor.tsx
  src/functions/CheckDateActivity.ts
  src/functions/CreateActivity.tsx
  src/functions/DeleteActivity.ts
  src/functions/EditActivity.ts
  src/functions/EditSubject.ts
  src/functions/FinalizedActivity.ts
  src/functions/Subjects/ActivateExamFunction.ts
  src/functions/Subjects/ControlExamStatusBasedOnTime.ts
  src/functions/Subjects/CreateExam.ts
  src/functions/Subjects/CreateSubject.ts
  src/functions/Subjects/DeleteExam.ts
  src/functions/Subjects/DeleteSubject.ts
  src/functions/Subjects/EditExam.ts
  src/functions/Subjects/EditSubject.ts
  src/functions/Subjects/FinalizeExam.ts
  src/functions/Subjects/FinalizeSubject.ts
  src/functions/Subjects/ReturnToActiveSubject.ts
  src/functions/Subjects/UpdateExamStatus.ts
  src/pages/TaskScreen.tsx
Labels: Front-End, Back-End, Firebase

#119 [ PULLREQUEST ] - Integralizando as funções de CRUD na LibraryPage.
  src/components/Library/editBook.tsx
  src/components/LibraryScreen.tsx
  src/functions/FinalizedBook.ts
Labels: Front-End, Back-End, Firebase

#120 [ PULLREQUEST ] - Integralizando as funções de CRUD na TasksPage.
  src/components/Activities/SearchDropdown.tsx
  src/components/Activities/StatusComponent.tsx
  src/components/Activities/createActivity.tsx
  src/components/Activities/editActivity.tsx
  src/components/ActivitiesComponent.tsx
  src/functions/CreateActivity.tsx
  src/functions/DeleteActivity.ts
  src/functions/EditActivity.ts
  src/pages/TaskScreen.tsx
Labels: Front-End, Back-End, Firebase

#126 Correção de bugs do calendário
  src/components/Calendar/CalendarFooter.tsx
  src/components/Calendar/DataImportante.tsx
  src/components/Calendar/DataProvas.tsx
  src/components/Calendar/DataTarefas.tsx
  src/functions/Calendar/fetchBookDates.ts
  src/functions/Calendar/fetchExamDates.ts
  src/functions/Calendar/fetchTaskDates.ts
Labels: Bug

#128 Atualização na documentação sobre execução do projeto e arquitetura
  README.md
  documentation/mkdocs/docs/Arquitetura.md
  documentation/mkdocs/docs/assets/newArchitecture.png
Labels: Documentação

#133 Subjects e Specific subjects - correção de bugs
  src/components/Subject/EditExamDialog.tsx
  src/components/Subject/EditSubjectComponent.tsx
  src/functions/Subjects/ControlExamStatusBasedOnTime.ts
  src/functions/Subjects/EditSubject.ts
Labels: Back-End, Firebase

#135 Correção de bugs da library page.
  src/components/Library/createLibrary.tsx
  src/components/Library/editBook.tsx
  src/components/LibraryScreen.tsx
  src/functions/CreateLibrary.tsx
  src/functions/EditBook.tsx
  src/functions/FinalizedBook.ts
  src/pages/Library.tsx
Labels: Bug, Front-End, Back-End

#140 Correção de Bugs Gerais das páginas
  src/components/Activities/SearchDropdown.tsx
  src/components/Activities/editActivity.tsx
  src/components/Calendar/DataLivros.tsx
  src/components/Library/createLibrary.tsx
  src/components/Subject/ExamDialogComponent.tsx
  src/components/Subject/createSubject.tsx
  src/functions/Calendar/fetchBookDates.ts
Labels: Front-End, Back-End

#143 Adição de componente de provas ao Dashboard
  src/components/Dashboard/DashboardExamsComponent.tsx
Labels: Front-End, Back-End, Firebase

#145 Merge da página de Cardapio na main
  src/components/Cardapio/DisplayMenu.tsx
  src/components/Cardapio/FeaturesCardapio.tsx
  src/components/Cardapio/LinksCardapioFazenda.tsx
  src/components/Cardapio/LinksCardapioGama.tsx
  src/components/Cardapio/LinksCardapioPlanaltina.tsx
  src/components/Cardapio/Navbar4.tsx
  src/components/Cardapio/linksCardapioDarcy.tsx
  src/functions/Cardapio/fetchDarcy.tsx
  src/functions/Cardapio/fetchFazenda.tsx
  src/functions/Cardapio/fetchGama.tsx
  src/functions/Cardapio/fetchPlanaltina.tsx
  src/pages/Menu.tsx
Labels: Front-End, Firebase

#146 [PULLREQUEST] - Atualizações e realizações feitas na branch TestsPage para a branch Main.
  documentation/mkdocs/docs/Reunioes/Reuniao19.md
  documentation/mkdocs/docs/Reunioes/Reuniao20.md
  documentation/mkdocs/docs/Reunioes/Reuniao21.md
  documentation/mkdocs/docs/Reunioes/Reuniao22.md
  documentation/mkdocs/docs/Reunioes/Reuniao23.md
  documentation/mkdocs/docs/Sprints/Sprint10.md
  documentation/mkdocs/docs/Sprints/Sprint11.md
  documentation/mkdocs/docs/Sprints/Sprint12.md
  documentation/mkdocs/docs/Sprints/Sprint9.md
  src/components/Dashboard/DashboardExamsComponent.tsx
  src/functions/Subjects/ControlExamStatusBasedOnTime.ts
  src/pages/Dashboard.tsx
Labels: Bug, Documentação, Front-End

#147 Estilização dos componentes da página de DashBoard, da sideBar e Header.
  src/components/Dashboard/DashBoardActivitiesComponent.tsx
  src/components/Dashboard/DashboardLinksCard.tsx
  src/components/Dashboard/DashboardSubjects.tsx
  src/components/Dashboard/DashboardTaskComponent.tsx
  src/components/Dashboard/Navbar.tsx
  src/components/Header.tsx
  src/components/NotificationSettingsModal.tsx
  src/components/SideBar.tsx
  src/pages/Dashboard.tsx
  src/pages/EventsPage.tsx
  src/routes/index.tsx
Labels: Front-End, Back-End, Firebase

#149 Atualização da documentação do projeto
  README.md
  WebScraping/README.md
  documentation/mkdocs/README.md
  documentation/mkdocs/docs/Requisitos.md
  documentation/mkdocs/docs/Sprints/Sprint12.md
  documentation/mkdocs/mkdocs.yml
Labels: Documentação

#153 Close(#141): Adição de funcionalidade das configurações das notificações.
  src/components/Header.tsx
  src/components/NotificationSettingsModal.tsx
  src/functions/CreateUserInfo.ts
  src/functions/Notifications/NotificationsFunctions.ts
Labels: Back-End, Firebase

#154 Close (#152): Resolvido bug de status das provas
  src/functions/Subjects/ControlExamStatusBasedOnTime.ts
  src/functions/Subjects/DeleteExam.ts
Labels: Bug, Back-End

#156 Finalizando detalhes da página de provas.
  src/components/Subject/EditExamDialog.tsx
Labels: Front-End, Low Priority

#159 Adição de workflow de testes de build em Pull Requests para a branch Main
  .github/workflows/build.yml
Labels: Back-End

#160 Correção de erros do TypeScript
  src/components/Activities/SearchDropdown.tsx
  src/components/Activities/StatusComponent.tsx
  src/components/Activities/createActivity.tsx
  src/components/Activities/editActivity.tsx
  src/components/ActivitiesComponent.tsx
  src/components/Calendar/CalendarNavbar.tsx
  src/components/Cardapio/Navbar4.tsx
  src/components/Dashboard/DashboardExamsComponent.tsx
  src/components/Dashboard/DashboardSubjects.tsx
  src/components/Exams/CreateExamDialog.tsx
  src/components/Exams/EditExamDialog.tsx
  src/components/Exams/ExamsComponent.tsx
  src/components/Exams/ExamsDataTableConstructor.tsx
  src/components/Exams/examInterfaces.tsx
  src/components/Header.tsx
  src/components/Input.tsx
  src/components/Library/createLibrary.tsx
  src/components/Library/editBook.tsx
  src/components/LibraryScreen.tsx
  src/components/SideBar.tsx
  src/components/SignIn/Checkbox.tsx
  src/components/SignIn/SignInCard.tsx
  src/components/SignUpCard.tsx
  src/components/SignUserCard.tsx
  src/components/Stats.tsx
  src/components/Subject/EditExamDialog.tsx
  src/components/Subject/EditSubjectComponent.tsx
  src/components/Subject/ExamDialogComponent.tsx
  src/components/Subject/SpecificSubjectComponents.tsx
  src/components/Subject/SpecificSubjectTasks.tsx
  src/components/Subject/SubjectDetailsComponent.tsx
  src/components/Subject/SubjectDialogComponent.tsx
  src/components/Subject/SubjectSpecificExams.tsx
  src/components/Subject/SubjectsComponents.tsx
  src/components/Subject/createSubject.tsx
  src/components/Subject/subjectsCardConstructor.tsx
  src/functions/CreateLibrary.tsx
  src/functions/EditActivity.ts
  src/functions/EditBook.tsx
  src/functions/Exams/ActivateExamFunction.ts
  src/functions/Exams/ControlExamStatusBasedOnTime.ts
  src/functions/Exams/CreateExam.ts
  src/functions/Exams/DeleteExam.ts
  src/functions/Exams/EditExam.ts
  src/functions/Exams/FinalizeExam.ts
  src/functions/FormatDate.ts
  src/functions/FormatTime.ts
  src/functions/SignIn/SignIn.ts
  src/functions/SignUp.ts
  src/functions/Subjects/CreateExam.ts
  src/functions/Subjects/CreateSubject.ts
  src/functions/Subjects/DeleteSubject.ts
  src/functions/Subjects/EditSubject.ts
  src/functions/Subjects/FinalizeSubject.ts
  src/pages/Library.tsx
  src/pages/Subjects.tsx
  src/pages/TaskScreen.tsx
Labels: Bug, Back-End, Firebase

#162 Adição de teste de build em push pra main
  .github/workflows/build.yml
Labels: Back-End

#164 [PULLREQUEST] - Reorganização de locais de armazenamento em pastas.
  src/components/Activities/ActivitiesComponent.tsx
  src/components/Activities/createActivity.tsx
  src/components/Activities/editActivity.tsx
  src/components/Calendar.tsx
  src/components/Exercises.tsx
  src/components/Library/LibraryScreen.tsx
  src/components/Library/createLibrary.tsx
  src/components/Library/editBook.tsx
  src/components/Profile/Stats.tsx
  src/components/Profile/UserInfo.tsx
  src/components/SignUp/SignUpCard.tsx
  src/components/SignUp/SignUserCard.tsx
  src/functions/Activities/CreateActivity.tsx
  src/functions/Activities/DeleteActivity.ts
  src/functions/Activities/EditActivity.ts
  src/functions/Activities/FinalizedActivity.ts
  src/functions/Library/CreateLibrary.tsx
  src/functions/Library/DeleteBook.ts
  src/functions/Library/EditBook.tsx
  src/functions/Library/FinalizedBook.ts
  src/functions/SignUp/CreateUserInfo.ts
  src/functions/SignUp/SignUp.ts
  src/functions/Subjects/DeleteSubject.ts
  src/functions/Subjects/FinalizeSubject.ts
  src/pages/Library.tsx
  src/pages/Profile.tsx
  src/pages/SignUp.tsx
  src/pages/SignUser.tsx
  src/pages/TaskScreen.tsx
  src/routes/index.tsx
Labels: Back-End, High Priority
